update COMPANY set CHANGE_DATE = now() where CHANGE_DATE < CREATE_DATE ;
update CONTRACTS set SIGNDATE = now() where SIGNDATE < CREATE_DATE ;
update CONTRACTS set CHANGE_DATE = now() where CHANGE_DATE < CREATE_DATE ;
update CONTRACTS set end_DATE = SIGNDATE + INTERVAL 1 YEAR ;
update AGENT_COMPANY set AG_CONTRACT_DATE = CREATE_DATE + INTERVAL 1 MONTH WHERE AG_CONTRACT_DATE <CREATE_DATE ;
update AGENT_COMPANY set CHANGE_DATE = now() where CHANGE_DATE < CREATE_DATE ;
update AGENTS set CHANGE_DATE = now() where CHANGE_DATE < CREATE_DATE ;
update REQUEST set BILL_SUM = KKT_PRICE_ID * COUNT_KKT ;
UPDATE REQUEST SET BILL_SUM_WITH_DISCOUNT = BILL_SUM * 0.8 WHERE BILL_SUM_WITH_DISCOUNT > BILL_SUM ;
UPDATE REQUEST SET SIGNDATE = now() WHERE SIGNDATE <CREATE_DATE;
UPDATE REQUEST SET STATUS_CHANGE_DATE = SIGNDATE +INTERVAL 1 DAY WHERE STATUS_CHANGE_DATE <SIGNDATE ;
UPDATE kkt SET START_DATE = CREATE_DATE + INTERVAL 1 DAY WHERE START_DATE < CREATE_DATE ;
UPDATE KKT SET END_DATE = START_DATE + INTERVAL 15 MONTH WHERE END_DATE < START_DATE ;
UPDATE kkt SET DEACTIVATION_DATE = END_DATE WHERE ACTIVATED is FALSE; 
UPDATE KKT SET DEACTIVATION_DATE = NULL WHERE ACTIVATED IS TRUE;
UPDATE TRADE_POINT SET CHANGE_DATE = now() where CHANGE_DATE < CREATE_DATE ;
UPDATE USERS SET CHANGE_DATE = now() where CHANGE_DATE < CREATE_DATE ;
update USERS set MADE_ID = (1 + rand()*20);
UPDATE AGENTS SET CHANGE_DATE = now() where CHANGE_DATE < CREATE_DATE ;
UPDATE users SET MADE_ID = NULL WHERE MADE_ID =0;
ALTER TABLE USERS DROP COLUMN company_id;
ALTER TABLE kkt DROP COLUMN company_id;
ALTER TABLE REQUEST DROP COLUMN company_id;
ALTER TABLE contracts MODIFY COLUMN company_id INT UNSIGNED NOT NULL;
-- Добавляем внешние ключи
ALTER TABLE CONTRACTS DROP FOREIGN KEY contracts_company_id_fk;
ALTER TABLE CONTRACTS 
  ADD CONSTRAINT contracts_company_id_fk 
    FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE kkt MODIFY COLUMN contract_id INT UNSIGNED NOT NULL;
-- Добавляем внешние ключи
ALTER TABLE kkt 
  ADD CONSTRAINT kkt_contract_id_fk 
    FOREIGN KEY (contract_id) REFERENCES contracts(id);
ALTER TABLE contracts MODIFY COLUMN company_id INT UNSIGNED NOT NULL;
-- Добавляем внешние ключи
ALTER TABLE TRADE_POINT MODIFY COLUMN company_id INT UNSIGNED NOT NULL;
ALTER TABLE TRADE_POINT 
  ADD CONSTRAINT trade_point_company_id_fk 
    FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE contracts MODIFY COLUMN company_id INT UNSIGNED NOT NULL;
-- Добавляем внешние ключи
ALTER TABLE USERS CHANGE COLUMN contract_id company_id INT UNSIGNED NOT NULL;
DESC users;
ALTER TABLE users 
  ADD CONSTRAINT users_company_id_fk 
    FOREIGN KEY (company_id) REFERENCES company(id);
ALTER TABLE AGENTS MODIFY COLUMN agent_company_id INT UNSIGNED NOT NULL;
-- Добавляем врешние ключи
ALTER TABLE AGENTS 
  ADD CONSTRAINT agents_agent_company_id_fk 
    FOREIGN KEY (agent_company_id) REFERENCES agent_company(id);
ALTER TABLE REQUEST MODIFY COLUMN contract_id INT UNSIGNED NOT NULL;
-- Добавляем врешние ключи
ALTER TABLE REQUEST 
  ADD CONSTRAINT request_contract_id_fk 
    FOREIGN KEY (contract_id) REFERENCES contracts(id);
